name: 'Hello World'
description: 'Greet someone'
inputs:
  path-to-config:
    description: 'path to .json file in the repo'
    required: true
  branch:
    description: 'branch that triggered the workflow run'
    required: true
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--config'
    - ${{ inputs.path-to-config }}
    - '--branch'
    - ${{ inputs.branch }}
