name: 'Release Manifest'
description: 'Create release manifest once all artifacts are available in the release'
inputs:
  path-to-config:
    description: 'path to .json file in the repo'
    required: true
  tag:
    description: 'tag identifying the release whose assets should be used'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--config'
    - ${{ inputs.path-to-config }}
    - '--tag'
    - ${{ inputs.tag }}
