name: 'Release Manifest'
description: 'Create release manifest once all artifacts are available in the release'
inputs:
  path-to-config:
    description: 'path to .json file in the repo'
    required: true
  branch:
    description: 'branch that triggered the workflow run'
    required: true

# Should output one or more files to /github/workspace or $GITHUB_WORKSPACE
# See https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#accessing-files-created-by-a-container-action

# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--config'
    - ${{ inputs.path-to-config }}
    - '--branch'
    - ${{ inputs.branch }}
